//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// Jigsaw_res.rc

#define IDS_APPNAME                         100
#define IDS_GENERATE                        101
#define IDS_INVALIDSTRING                   102
#define IDS_TEXTTOOLONG                     103
#define IDS_A3                              104
#define IDS_A4                              105
#define IDS_A5                              106
#define IDS_B4                              107
#define IDS_B5                              108
#define IDS_PORTRAIT                        109
#define IDS_LANDSCAPE                       110
#define IDS_LOGO                            111
#define IDS_COPYFILEFAILED                  112
#define IDS_SUCCEEDED                       113
#define IDS_PROCESSINGNOW                   114
#define IDS_OPENFILTER                      115
#define IDS_SET_BACKGROUND_IMAGE            116
#define IDS_SUSIE_IMAGES                    117

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
